// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqrJgzcsUHDYn_dV1J1p0WPN6f3O-jL_0',
    appId: '1:156753959180:web:ffdb3623ed4a8febeb5129',
    messagingSenderId: '156753959180',
    projectId: 'deep-link-test-15288',
    authDomain: 'deep-link-test-15288.firebaseapp.com',
    storageBucket: 'deep-link-test-15288.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbEn_9wsMEb_Oj4bHCIlCoovBw7iNFzc',
    appId: '1:156753959180:android:a70763e8181ce910eb5129',
    messagingSenderId: '156753959180',
    projectId: 'deep-link-test-15288',
    storageBucket: 'deep-link-test-15288.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVTnnjIccsSvBfSsHjDc1bQv-FTbl0KI',
    appId: '1:156753959180:ios:2502f0afc8767000eb5129',
    messagingSenderId: '156753959180',
    projectId: 'deep-link-test-15288',
    storageBucket: 'deep-link-test-15288.appspot.com',
    iosBundleId: 'luancaius.examples.fcm.fcmflutter',
  );
}
